// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exam.proto

package exam

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExamRequest struct {
	ExamName             string   `protobuf:"bytes,3,opt,name=exam_name,json=examName,proto3" json:"exam_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExamRequest) Reset()         { *m = ExamRequest{} }
func (m *ExamRequest) String() string { return proto.CompactTextString(m) }
func (*ExamRequest) ProtoMessage()    {}
func (*ExamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70e600da0d9a195d, []int{0}
}

func (m *ExamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExamRequest.Unmarshal(m, b)
}
func (m *ExamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExamRequest.Marshal(b, m, deterministic)
}
func (m *ExamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExamRequest.Merge(m, src)
}
func (m *ExamRequest) XXX_Size() int {
	return xxx_messageInfo_ExamRequest.Size(m)
}
func (m *ExamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExamRequest proto.InternalMessageInfo

func (m *ExamRequest) GetExamName() string {
	if m != nil {
		return m.ExamName
	}
	return ""
}

type ExamResponse struct {
	ExamNo               string   `protobuf:"bytes,1,opt,name=exam_no,json=examNo,proto3" json:"exam_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExamResponse) Reset()         { *m = ExamResponse{} }
func (m *ExamResponse) String() string { return proto.CompactTextString(m) }
func (*ExamResponse) ProtoMessage()    {}
func (*ExamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_70e600da0d9a195d, []int{1}
}

func (m *ExamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExamResponse.Unmarshal(m, b)
}
func (m *ExamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExamResponse.Marshal(b, m, deterministic)
}
func (m *ExamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExamResponse.Merge(m, src)
}
func (m *ExamResponse) XXX_Size() int {
	return xxx_messageInfo_ExamResponse.Size(m)
}
func (m *ExamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExamResponse proto.InternalMessageInfo

func (m *ExamResponse) GetExamNo() string {
	if m != nil {
		return m.ExamNo
	}
	return ""
}

func init() {
	proto.RegisterType((*ExamRequest)(nil), "exam.ExamRequest")
	proto.RegisterType((*ExamResponse)(nil), "exam.ExamResponse")
}

func init() { proto.RegisterFile("exam.proto", fileDescriptor_70e600da0d9a195d) }

var fileDescriptor_70e600da0d9a195d = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xad, 0x48, 0xcc,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xb4, 0xb8, 0xb8, 0x5d, 0x2b,
	0x12, 0x73, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xa4, 0xb9, 0x38, 0x41, 0xc2, 0xf1,
	0x79, 0x89, 0xb9, 0xa9, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x1c, 0x20, 0x01, 0xbf, 0xc4,
	0xdc, 0x54, 0x25, 0x75, 0x2e, 0x1e, 0x88, 0xda, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x71,
	0x2e, 0x76, 0x88, 0xe2, 0x7c, 0x09, 0x46, 0xb0, 0x52, 0x36, 0xb0, 0xd2, 0x7c, 0x23, 0x3b, 0x88,
	0xa1, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0xfa, 0x5c, 0x6c, 0xc1, 0xa5, 0x49, 0xb9,
	0x99, 0x25, 0x42, 0x82, 0x7a, 0x60, 0x07, 0x20, 0xd9, 0x28, 0x25, 0x84, 0x2c, 0x04, 0x31, 0x38,
	0x89, 0x0d, 0xec, 0x42, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x60, 0xee, 0x7f, 0xaf,
	0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ExamServiceClient is the client API for ExamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExamServiceClient interface {
	Submit(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamResponse, error)
}

type examServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExamServiceClient(cc grpc.ClientConnInterface) ExamServiceClient {
	return &examServiceClient{cc}
}

func (c *examServiceClient) Submit(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamResponse, error) {
	out := new(ExamResponse)
	err := c.cc.Invoke(ctx, "/exam.ExamService/Submit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExamServiceServer is the server API for ExamService service.
type ExamServiceServer interface {
	Submit(context.Context, *ExamRequest) (*ExamResponse, error)
}

// UnimplementedExamServiceServer can be embedded to have forward compatible implementations.
type UnimplementedExamServiceServer struct {
}

func (*UnimplementedExamServiceServer) Submit(ctx context.Context, req *ExamRequest) (*ExamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}

func RegisterExamServiceServer(s *grpc.Server, srv ExamServiceServer) {
	s.RegisterService(&_ExamService_serviceDesc, srv)
}

func _ExamService_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/exam.ExamService/Submit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).Submit(ctx, req.(*ExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "exam.ExamService",
	HandlerType: (*ExamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _ExamService_Submit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exam.proto",
}
