info:
  name: kit
  env: local  #本地开发:local, 测试:test, 线上:production
api_port:
  sc: 5001
  tmr: 5002
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: password
  database: test
  parameters: false
  max_idle_conn: 40
  max_open_conn: 40
redis:
  addr: 127.0.0.1:6379
  password: password
  db: 0
jwt:
  secret: secret
  issuer: 127.0.0.1
  expire: 10
cache:
  drive: redis
  expire: 30                    # 自动过期时间 单位秒
log:
  writer: file,stderr           # 日志输出位置 file输出到文件 stderr输出到屏幕 可多选
  format: json                  # 日志格式 json 或 text
  level: error                  # 日志级别
  file:
    name: api.log               # 日志文件名称
    path: ./                    # 日志文件目录
    rotation_open: true         # 日志是否根据时间切割 true开启 false关闭
    rotation_unit: minute       # 日志切割时间单位 minute分钟 hour小时 day天
    rotation_time: 1            # 日志切割时间
    rotation_time_save: 10      # 日志保存时间
elasticsearch:
  url: http://127.0.0.1:9200,http://127.0.0.1:9201
  sniff: false