// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	SmsCode              string   `protobuf:"bytes,2,opt,name=smsCode,proto3" json:"smsCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *AuthRequest) GetSmsCode() string {
	if m != nil {
		return m.SmsCode
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TokenType            string   `protobuf:"bytes,2,opt,name=tokenType,proto3" json:"tokenType,omitempty"`
	ExpiresIn            int32    `protobuf:"varint,3,opt,name=expiresIn,proto3" json:"expiresIn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *Token) GetExpiresIn() int32 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

type AuthResponse struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type TokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenRequest) Reset()         { *m = TokenRequest{} }
func (m *TokenRequest) String() string { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()    {}
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *TokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRequest.Unmarshal(m, b)
}
func (m *TokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRequest.Marshal(b, m, deterministic)
}
func (m *TokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRequest.Merge(m, src)
}
func (m *TokenRequest) XXX_Size() int {
	return xxx_messageInfo_TokenRequest.Size(m)
}
func (m *TokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRequest proto.InternalMessageInfo

func (m *TokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserResponse struct {
	StudentUserId        int64    `protobuf:"varint,1,opt,name=student_user_id,json=studentUserId,proto3" json:"student_user_id,omitempty"`
	StudentUserNo        int64    `protobuf:"varint,2,opt,name=student_user_no,json=studentUserNo,proto3" json:"student_user_no,omitempty"`
	StudentUserName      string   `protobuf:"bytes,3,opt,name=student_user_name,json=studentUserName,proto3" json:"student_user_name,omitempty"`
	StudentUserStatus    int32    `protobuf:"varint,4,opt,name=student_user_status,json=studentUserStatus,proto3" json:"student_user_status,omitempty"`
	StudentUserMobile    string   `protobuf:"bytes,5,opt,name=student_user_mobile,json=studentUserMobile,proto3" json:"student_user_mobile,omitempty"`
	StudentUserHead      string   `protobuf:"bytes,6,opt,name=student_user_head,json=studentUserHead,proto3" json:"student_user_head,omitempty"`
	LastLoginIp          int64    `protobuf:"varint,7,opt,name=last_login_ip,json=lastLoginIp,proto3" json:"last_login_ip,omitempty"`
	LastLoginTime        string   `protobuf:"bytes,8,opt,name=last_login_time,json=lastLoginTime,proto3" json:"last_login_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetStudentUserId() int64 {
	if m != nil {
		return m.StudentUserId
	}
	return 0
}

func (m *UserResponse) GetStudentUserNo() int64 {
	if m != nil {
		return m.StudentUserNo
	}
	return 0
}

func (m *UserResponse) GetStudentUserName() string {
	if m != nil {
		return m.StudentUserName
	}
	return ""
}

func (m *UserResponse) GetStudentUserStatus() int32 {
	if m != nil {
		return m.StudentUserStatus
	}
	return 0
}

func (m *UserResponse) GetStudentUserMobile() string {
	if m != nil {
		return m.StudentUserMobile
	}
	return ""
}

func (m *UserResponse) GetStudentUserHead() string {
	if m != nil {
		return m.StudentUserHead
	}
	return ""
}

func (m *UserResponse) GetLastLoginIp() int64 {
	if m != nil {
		return m.LastLoginIp
	}
	return 0
}

func (m *UserResponse) GetLastLoginTime() string {
	if m != nil {
		return m.LastLoginTime
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "auth.AuthRequest")
	proto.RegisterType((*Token)(nil), "auth.Token")
	proto.RegisterType((*AuthResponse)(nil), "auth.AuthResponse")
	proto.RegisterType((*TokenRequest)(nil), "auth.TokenRequest")
	proto.RegisterType((*UserResponse)(nil), "auth.UserResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x4f, 0xe3, 0x30,
	0x10, 0x55, 0x3f, 0xd2, 0x8f, 0x49, 0xab, 0xaa, 0xde, 0xd5, 0xca, 0x5a, 0xed, 0xa1, 0x1b, 0x21,
	0x54, 0x71, 0xa8, 0x44, 0xf9, 0x01, 0x08, 0x71, 0xa1, 0x12, 0x70, 0x48, 0x0b, 0x12, 0xa7, 0xc8,
	0x25, 0x23, 0x6a, 0x91, 0xc4, 0x69, 0xec, 0x20, 0xf8, 0xbb, 0xfc, 0x12, 0x64, 0xc7, 0x6d, 0x1d,
	0xca, 0xcd, 0xf3, 0xe6, 0xcd, 0xc7, 0xf3, 0x1b, 0x00, 0x56, 0xaa, 0xcd, 0x2c, 0x2f, 0x84, 0x12,
	0xa4, 0xad, 0xdf, 0xc1, 0x25, 0xf8, 0x57, 0xa5, 0xda, 0x84, 0xb8, 0x2d, 0x51, 0x2a, 0xf2, 0x07,
	0x3a, 0xa9, 0x58, 0xf3, 0x04, 0x69, 0x63, 0xd2, 0x98, 0xf6, 0x43, 0x1b, 0x11, 0x0a, 0x5d, 0x99,
	0xca, 0x6b, 0x11, 0x23, 0x6d, 0x9a, 0xc4, 0x2e, 0x0c, 0x9e, 0xc0, 0x5b, 0x89, 0x57, 0xcc, 0xc8,
	0x6f, 0xf0, 0x94, 0x7e, 0xd8, 0xca, 0x2a, 0x20, 0xff, 0xa0, 0x6f, 0x1e, 0xab, 0x8f, 0x7c, 0x57,
	0x7a, 0x00, 0x74, 0x16, 0xdf, 0x73, 0x5e, 0xa0, 0x5c, 0x64, 0xb4, 0x35, 0x69, 0x4c, 0xbd, 0xf0,
	0x00, 0x04, 0xe7, 0x30, 0xa8, 0x76, 0x93, 0xb9, 0xc8, 0x24, 0x92, 0xff, 0xee, 0x04, 0x7f, 0xee,
	0xcf, 0x8c, 0x1a, 0x33, 0xdd, 0x8e, 0x0b, 0x4e, 0x60, 0x50, 0xc5, 0x56, 0xcf, 0x8f, 0x4b, 0x05,
	0x9f, 0x4d, 0x18, 0x3c, 0x48, 0x2c, 0xf6, 0x9d, 0x4f, 0x61, 0x24, 0x55, 0x19, 0x63, 0xa6, 0xa2,
	0x52, 0x62, 0x11, 0xf1, 0xd8, 0x14, 0xb4, 0xc2, 0xa1, 0x85, 0x35, 0x7b, 0x11, 0x1f, 0xf1, 0x32,
	0x61, 0x34, 0xd5, 0x79, 0xf7, 0x82, 0x9c, 0xc1, 0xb8, 0xce, 0x63, 0x29, 0x1a, 0x7d, 0xfd, 0x70,
	0xe4, 0x32, 0x59, 0x8a, 0x64, 0x06, 0xbf, 0x6a, 0x5c, 0xa9, 0x98, 0x2a, 0x25, 0x6d, 0x9b, 0xdf,
	0x18, 0x3b, 0xec, 0xa5, 0x49, 0x1c, 0xf1, 0xad, 0x5f, 0x9e, 0xe9, 0xee, 0xf2, 0xef, 0x2a, 0xeb,
	0xbe, 0xef, 0xb2, 0x41, 0x16, 0xd3, 0xce, 0xd1, 0x2e, 0x37, 0xc8, 0x62, 0x12, 0xc0, 0x30, 0x61,
	0x52, 0x45, 0x89, 0x78, 0xe1, 0x59, 0xc4, 0x73, 0xda, 0x35, 0xea, 0x7c, 0x0d, 0xde, 0x6a, 0x6c,
	0x91, 0xeb, 0x3f, 0x70, 0x38, 0x8a, 0xa7, 0x48, 0x7b, 0xa6, 0xdb, 0x70, 0xcf, 0x5a, 0xf1, 0x14,
	0xe7, 0xdb, 0xea, 0xb2, 0x96, 0x58, 0xbc, 0xf1, 0x67, 0x2d, 0xd3, 0x33, 0x39, 0x32, 0xae, 0x6c,
	0x73, 0xae, 0xee, 0x2f, 0x71, 0x21, 0x6b, 0xc9, 0x1c, 0x7a, 0x8f, 0x2c, 0xe1, 0x31, 0x53, 0x48,
	0x88, 0xeb, 0x74, 0xbd, 0xc6, 0xb5, 0x71, 0xdd, 0x31, 0x97, 0x7d, 0xf1, 0x15, 0x00, 0x00, 0xff,
	0xff, 0x31, 0xd4, 0xa9, 0x9d, 0xe7, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	Login(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Validate(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Login(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Validate(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	Login(context.Context, *AuthRequest) (*AuthResponse, error)
	Validate(context.Context, *TokenRequest) (*UserResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) Login(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServiceServer) Validate(ctx context.Context, req *TokenRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Validate(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _AuthService_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
