// Code generated by protoc-gen-go. DO NOT EDIT.
// source: barrier.proto

package barrier

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	BarrierGameId        int64    `protobuf:"varint,1,opt,name=barrier_game_id,json=barrierGameId,proto3" json:"barrier_game_id,omitempty"`
	KnowledgeNo          int64    `protobuf:"varint,2,opt,name=knowledge_no,json=knowledgeNo,proto3" json:"knowledge_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_14de48ca7744c6fa, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetBarrierGameId() int64 {
	if m != nil {
		return m.BarrierGameId
	}
	return 0
}

func (m *Request) GetKnowledgeNo() int64 {
	if m != nil {
		return m.KnowledgeNo
	}
	return 0
}

type Response struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_14de48ca7744c6fa, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*Request)(nil), "barrier.Request")
	proto.RegisterType((*Response)(nil), "barrier.Response")
}

func init() { proto.RegisterFile("barrier.proto", fileDescriptor_14de48ca7744c6fa) }

var fileDescriptor_14de48ca7744c6fa = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4a, 0x2c, 0x2a,
	0xca, 0x4c, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x42, 0xb8,
	0xd8, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xd4, 0xb8, 0xf8, 0xa1, 0xa2, 0xf1, 0xe9,
	0x89, 0xb9, 0xa9, 0xf1, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x30, 0xbd, 0xee,
	0x89, 0xb9, 0xa9, 0x9e, 0x29, 0x42, 0x8a, 0x5c, 0x3c, 0xd9, 0x79, 0xf9, 0xe5, 0x39, 0xa9, 0x29,
	0xe9, 0xa9, 0xf1, 0x79, 0xf9, 0x12, 0x4c, 0x60, 0x45, 0xdc, 0x70, 0x31, 0xbf, 0x7c, 0x25, 0x25,
	0x2e, 0x8e, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x31, 0x2e, 0xb6, 0xa2, 0xd4,
	0xe2, 0xd2, 0x9c, 0x12, 0xb0, 0x69, 0x1c, 0x41, 0x50, 0x9e, 0x91, 0x2d, 0x17, 0x9f, 0x13, 0xc4,
	0xdc, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x6d, 0x2e, 0x96, 0xe0, 0xec, 0xcc, 0x02,
	0x21, 0x01, 0x3d, 0x98, 0x63, 0xa1, 0x4e, 0x93, 0x12, 0x44, 0x12, 0x81, 0x18, 0x9b, 0xc4, 0x06,
	0xf6, 0x88, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x46, 0x27, 0xc1, 0x85, 0xd9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BarrierServiceClient is the client API for BarrierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BarrierServiceClient interface {
	Skip(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type barrierServiceClient struct {
	cc *grpc.ClientConn
}

func NewBarrierServiceClient(cc *grpc.ClientConn) BarrierServiceClient {
	return &barrierServiceClient{cc}
}

func (c *barrierServiceClient) Skip(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/barrier.BarrierService/Skip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BarrierServiceServer is the server API for BarrierService service.
type BarrierServiceServer interface {
	Skip(context.Context, *Request) (*Response, error)
}

// UnimplementedBarrierServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBarrierServiceServer struct {
}

func (*UnimplementedBarrierServiceServer) Skip(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Skip not implemented")
}

func RegisterBarrierServiceServer(s *grpc.Server, srv BarrierServiceServer) {
	s.RegisterService(&_BarrierService_serviceDesc, srv)
}

func _BarrierService_Skip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarrierServiceServer).Skip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/barrier.BarrierService/Skip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarrierServiceServer).Skip(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _BarrierService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "barrier.BarrierService",
	HandlerType: (*BarrierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Skip",
			Handler:    _BarrierService_Skip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "barrier.proto",
}
